Neos:
  Neos:
    fusion:
      autoInclude:
        Jonnitto.iFrame: true
    userInterface:
      translation:
        autoInclude:
          Jonnitto.iFrame:
            - 'NodeTypes/*'

Jonnitto:
  iFrame:
    width: '100%'
    defaultHeight: 400
    defaultStyle: 'background:transparent;border:none;'
    positionStyle: 'position:absolute;top:0;left:0;width:100%;height:100%;'
