Neos:
  Neos:
    fusion:
      autoInclude:
        Jonnitto.iFrame: true
    userInterface:
      translation:
        autoInclude:
          Jonnitto.iFrame:
            - 'NodeTypes/*'

Jonnitto:
  iFrame:
    container: true
    width: '100%'
    defaultHeight: 400
    defaultStyle: 'background:transparent;border:none;'
    positionStyle: 'position:absolute;top:0;left:0;width:100%;height:100%;'

Carbon:
  IncludeAssets:
    Packages:
      'Jonnitto.iFrame:ErrorCheck':
        Package: 'Jonnitto.iFrame'
        ConditionPrototype: 'Jonnitto.iFrame:ErrorCheck'
        General:
          Head:
            - Main.js[inline]
