Carbon:
  IncludeAssets:
    Packages:
      'Jonnitto.iFrame:ErrorCheck':
        Package: 'Jonnitto.iFrame'
        ConditionPrototype: 'Jonnitto.iFrame:Component.ErrorCheck'
        General:
          Head:
            - Main.js[inline]
